extends Node

class_name DiscordTypes

enum InteractionCallback
{
	PONG = 1,
	CHANNEL_MESSAGE_WITH_SOURCE = 4,
	DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE = 5,
	DEFERRED_UPDATE_MESSAGE = 6,
	UPDATE_MESSAGE = 7,
	APPLICATION_COMMAND_AUTOCOMPLETE_RESULT = 8,
	MODAL = 9,
	PREMIUM_REQUIRED = 10,
	LAUNCH_ACTIVITY = 12
}

enum Interaction
{
	PING = 1,
	APPLICATION_COMMAND = 2,
	MESSAGE_COMPONENT = 3,
	APPLICATION_COMMAND_AUTOCOMPLETE = 4,
	MODAL_SUBMIT = 5
}

enum Component
{
	ACTION_ROW = 1,
	BUTTON = 2,
	STRING_SELECT = 3,
	TEXT_INPUT = 4,
	USER_SELECT = 5,
	ROLE_SELECT = 6,
	MENTIONABLE_SELECT = 7,
	CHANNEL_SELECT = 8,
	SECTION = 9,
	TEXT_DISPLAY = 10,
	THUMBNAIL = 11,
	MEDIA_GALLERY = 12,
	FILE = 13,
	SEPARATOR = 14,
	CONTAINER = 17,
	LABEL = 18,
	FILE_UPLOAD = 19
}

enum TextInputStyle
{
	SHORT = 1,
	PARAGRAPH = 2
}

enum MessageFlag
{
	CROSSPOSTED = 1 << 0,
	IS_CROSSPOST = 1 << 1,
	SUPPRESS_EMBEDS = 1 << 2,
	SOURCE_MESSAGE_DELETED = 1 << 3,
	URGENT = 1 << 4,
	HAS_THREAD = 1 << 5,
	EPHEMERAL = 1 << 6,
	LOADING = 1 << 7,
	FAILED_TO_MENTION_SOME_ROLES_IN_THREAD = 1 << 8,
	SUPPRESS_NOTIFICATIONS = 1 << 12,
	IS_VOICE_MESSAGE = 1 << 13,
	HAS_SNAPSHOT = 1 << 14,
	IS_COMPONENTS_V2 = 1 << 15
}
